apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-multi-components-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-multi-components-repo
    app.kubernetes.io/part-of: multi-components-repo
  name: python-app-multi-components-repo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-app-multi-components-repo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-app-multi-components-repo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/kkanova-tenant/multi-components-repo/python-app-multi-components-repo@sha256:f3f615a90089e791ab2e0ff1e31b3831616b5a86f189faf753a20dfa167d7324
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
